# -*- coding: utf-8 -*-
"""Voice Assistant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlcFLS7vXXED8OVO1-x9sUDSlC2kEL4y
"""

!pip install SpeechRecognition

# Install necessary dependencies
!apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

# Install PyAudio
!pip install pyaudio

import speech_recognition as sr
import webbrowser
import datetime

def speak(text):
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.energy_threshold = 3000
        r.adjust_for_ambient_noise(source, duration=0.5)
        audio = r.record(source, duration=3)
        try:
            print("You said: " + r.recognize_google(audio))
        except sr.UnknownValueError:
            print("Could not understand audio")
        except sr.RequestError as e:
            print("Could not request results from Google Speech Recognition service; {0}".format(e))
    print(text)

def respond_to_hello():
    speak("Hello! How can I help you?")

def tell_time():
    current_time = datetime.datetime.now().strftime("%H:%M")
    speak("The current time is " + current_time)

def tell_date():
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    speak("Today's date is " + current_date)

def search_web(query):
    url = "https://www.google.com/search?q=" + query
    webbrowser.open(url)
    speak("Here is what I found on the web for your query: " + query)

def main():
    respond_to_hello()
    while True:
        r = sr.Recognizer()
        with sr.Microphone() as source:
            print("Listening...")
            audio = r.listen(source)
            try:
                text = r.recognize_google(audio).lower()
                if "time" in text:
                    tell_time()
                elif "date" in text:
                    tell_date()
                elif "search" in text:
                    query = text.split("for")[-1].strip()
                    search_web(query)
                elif "goodbye" in text or "bye" in text:
                    speak("Goodbye! Have a great day!")
                    break
                else:
                    speak("I'm sorry, I didn't understand that.")
            except sr.UnknownValueError:
                print("Could not understand audio")
            except sr.RequestError as e:
                print("Could not request results from Google Speech Recognition service; {0}".format(e))

if _name_ == "_main_":
    main()